node {
    properties([
            parameters([
                    choice(choices: ['Alexandre', 'Andrea'], description: 'Nome do familiar', name: 'irmao'),
            ])
    ])

    def imageName = 'NodeJS'

    stage('Print Input Params') {
        sh 'printenv'
    }
    stage('Checkout') {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/alexfbasa/docker-demo.git']]])
    }
}