node {
    properties([
            parameters([
                    choice(choices: ['Alexandre', 'Andrea'], description: 'Nome do familiar', name: 'irmao'),
            ])
    ])

    def imageName = 'NodeJS'

    stage('Print Input Params') {
        sh 'printenv'
    }
    stage('Checkout') {
        checkout scm
    }
}