version: '3'
services:
  web:
    container_name: tomcat
    image: tomcat
    restart: always
    build:
      context: tomcat
    ports:
      - "8080:8090"
    volumes:
      - "$PWD/tomcat_home:/usr/local/tomcat"
    networks:
      - net
networks:
  net: