version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins_ansible
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - './tasks-frontend/:/usr/local/tomcat/webapps/tasks-frontend/'
      - './tasks-backend/:/usr/local/tomcat/webapps/tasks-backend/'
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7
    networks:
      - net
  web:
    container_name: tomcat
    image: tomcat
    build:
      context: web
    ports:
      - "80:80"
    volumes:
      - './tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:rw'
      - './context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml:rw'
    networks:
      - net
  database:
    container_name: pgsql_db
    image: postgres:9.6
    ports:
      - "5433:5432"
    volumes:
      - "$PWD/db_home:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=db
  sonarqube:
    container_name: sonar
    image: sonarqube:7.9.2-community
    ports:
      - "9000:9000"
    networks:
      - net
    environment:
      - sonar.jdbc.url=jdbc:postgresql://pg-sonar:5432/sonar
    depends_on:
      - pg-sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  pg-sonar:
    container_name: pg-sonar
    image: postgres:9.6
    networks:
      - net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
networks:
  net: